### ISSUE TITLE
A Problem about Constant.UploadFrameInterval

### ISSUE THREAD

**Issue by sherlockcooper** [carmap-nsdi/CarMap#1]
I tried to implement carmap and we found that one line in `ReadAndParseConfigFile` requires property `Constant.UploadFrameInterval`.
```
upload_frame_interval = fSettings ["Constant.UploadFrameInterval"];
```
But in Config_File.yaml I didn't find such item. 
After I added it manually, I found that any value other than 1 will cause segmentation fault. If I set this value to 1 then carmap can not get consecutive map segment due to this part
```
if (ni % upload_frame_interval == 0 && is_upload_map_to_cloud == true)
        {
            cout << "CarMap checkpoint: Going to send a map update and reset mapping all over again" << endl;
            SLAM->SendMapAndReset(&e2e_logger, !upload_only_diff);
            cout << "Starting CarMap from scratch" << endl;
        }
```
How can I generate a trajectory with `UploadFrameInterval` value bigger than 1 without getting segmentation fault?

**Comment by fawadahm** [comment]
Sorry for not seeing this earlier. Were you able to figure out this problem? If not, could you please tell me if you've setup up the cloud service?

**Comment by fawadahm** [comment]
Closing this issue. The latest update solves this.
